---
go: 
  version: 1.9
verbose: true
repository:
  path: github.com/leominov/datalock
build:
  flags: -a -tags netgo
tarball:
  files:
    - README.md
    - LICENSE
crossbuild:
  platforms:
    - linux/amd64
    - linux/386
    - darwin/amd64
    - darwin/386
    - windows/amd64
    - windows/386
